### ISSUE TITLE
有的身份证 正确的但是校验显示不通过

### ISSUE THREAD

**Issue by outbegin** [jxlwqq/id-validator.py#16]
有的身份证 正确的但是校验显示不通过 不过我不能发出这类身份证 很尬尴

**Comment by jxlwqq** [comment]
有问题的ID可以发我邮箱，我测试一下

**Comment by outbegin** [comment]
客户隐私 不能发 我看看能不能找到 规律到时模拟生成一个 目前是11943笔 发现18笔这样的情况

**Comment by jxlwqq** [comment]
> 客户隐私 不能发 我看看能不能找到 规律到时模拟生成一个 目前是11943笔 发现18笔这样的情况

好的，谢谢。

**Comment by outbegin** [comment]
已发送

**Comment by jxlwqq** [comment]
优化了地址码启用年份和身份证出生年份的判断，试试看。
