### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '*'

### ISSUE THREAD

**Issue by GitOffice** [jxlwqq/id-validator.py#6]
请问调用is_valid 方法时候，出现这个错误提示，如何解决？
![qq 20190120181123](https://user-images.githubusercontent.com/1814649/51437872-178e5780-1cdf-11e9-8b6d-df77484d441d.png)

**Comment by jxlwqq** [comment]
方便给你的传参发上来吗？我这边测试一下。

**Comment by GitOffice** [comment]
> 方便给你的传参发上来吗？我这边测试一下。

当时那个号码没有print,我来定位一下.

**Comment by GitOffice** [comment]
问题找到了,是身份证号有问题.
