### ISSUE TITLE
获取地理位置没有判断有效结束时间

### ISSUE THREAD

**Issue by Ricky617** [jxlwqq/id-validator.py#7]
def get_address(address_code, birthday_code):
    """
    通过地址码与出生日期码获取地址信息
    :param address_code:
    :param birthday_code:
    :return:
    """
    address = ''
    address_code_timeline = data.get_address_code_timeline()
    timeline = address_code_timeline.get(address_code, '')
    if timeline != '':
        year = int(birthday_code[0:4])
        for key, val in enumerate(timeline):
            start_year = 0 if val['start_year'] == '' else int(val['start_year'])
            if (key == 0 and year < start_year) or year >= start_year:
                address = val['address']

    return address

只判断了start_year是否有效，没有判断end_year，导致有的地理位置错误

**Comment by Ricky617** [comment]
430302 应该是湘潭市，显示为邵阳市

**Comment by jxlwqq** [comment]
> 430302 应该是湘潭市，显示为邵阳市

@Ricky617 完整的ID方便发我吗，我测试一下。

**Comment by Ricky617** [comment]
4303021993

**Comment by Ricky617** [comment]
<class 'list'>: [{'address': '湘潭市', 'start_year': '', 'end_year': ''}, {'address': '邵阳市', 'start_year': 1982, 'end_year': 1983}]
93年应该是湘潭市

**Comment by Ricky617** [comment]
def get_address(address_code, birthday_code):
    """
    通过地址码与出生日期码获取地址信息
    :param address_code:
    :param birthday_code:
    :return:
    """
    address = ''
    address_code_timeline = data.get_address_code_timeline()
    timeline = address_code_timeline.get(address_code, '')
    if timeline != '':
        year = int(birthday_code[0:4])
        for key, val in enumerate(timeline):
            start_year = val['start_year']
            end_year = val['end_year']
            if start_year != '' and end_year != '' and start_year <= year <= end_year:
                address = val['address']
                break
            if start_year != '' and end_year == '' and year >= start_year:
                address = val['address']
            if start_year == '' and end_year != '' and year <= end_year:
                address = val['address']
            if start_year == '' and end_year == '':
                address = val['address']
    return address
不知道这么写行不行

**Comment by jxlwqq** [comment]
谢谢，我周末复查一下，最近加班没时间搞。

**Comment by jxlwqq** [comment]
计划本周修复

**Comment by jxlwqq** [comment]
已发布：https://pypi.org/project/id-validator/1.0.14/
